<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SOLUTIONS S.A</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="refresh" content="3600" />
	<link rel="icon" href="favicon.ico" type="image/x-icon" />
	<link rel="shortcut icon" href="favicon.ico" />
	<link  rel="stylesheet" type="text/css" href="./css/style.css">
	<script language="JavaScript" type="text/javascript" src="./js/funciones.js"></script>
	<script language="JavaScript" type="text/javascript" src="./js/sha1.js"></script>
</head>
<body>
<div align="center">
<table><td><?php include("menu/menu.php"); ?></td></table>
<br>
</div>
