<div align="center">
<table  align="center">
<form id="form1" name="form1" method="POST" action="?w=addRuta">
<?php
	if($ruta){
		$title="Editar Ruta";
		foreach ($ruta as $dato) {
			$idruta=$dato['id'];
			$nombre=$dato['ruta'];
			$origen = $dato['origen'];
			$destino=$dato['destino'];
			$distancia=$dato['distancia'];
			$peso=$dato['peso'];
			$estadoa=$dato['estado'];
			
		}
	}else {
		$title="Nueva Ruta";
	}
	
?>
<input type='text' name='idruta' id='idruta' value='<?php echo $idruta;?>' hidden></input>
    <table class="uss" align="center">
	<th colspan='2'><h3><a href='?w=panel'><img title="Atras" src="img/left.gif"  /></a> <?php echo $title;?></h3></th></tr>
		<td><label>Nombre:</label><input type="text" style='text-transform:uppercase' class="textbox" name="nombre" id="nombre" required value='<?php echo $nombre;?>'></input></td><tr>
        <td><label>Origen:</label><input type="text" class="textbox" name="origen" id="origen" required value='<?php echo $origen;?>'></input></td><tr>
		<td><label>Destino:</label><input type="text" class="textbox" name="destino" id="destino" required value='<?php echo $destino;?>'></input></td><tr>
		<td><label>Distancia:</label><input type="number" class="textbox" name="distancia" id="distancia" required value='<?php echo $distancia;?>'></input></td><tr>
		<td><label>Peso:</label><input type="number" class="textbox"name="peso" id="peso" required value='<?php echo $peso;?>'></input></td><tr>
		<td><label>Estado:</label>
		<select class="textbox" name="estado" id="estado" required >
		
		<?php 
	
			echo "<option value=''>Seleccione...</option>;";
				foreach ($estados_ruta as $estado) {
					
					if($estadoa==$estado['id']){
						echo "<option required value=".$estado['id']." selected>".$estado['nombre']."</option>";	
					}else{
						echo "<option required value=".$estado['id'].">".$estado['nombre']."</option>";	
					}
				}
		?>
		</select>
		</td><tr>
		<td colspan=2><center><label>Tipo de carga:</label></center>
		</td><tr>
		<td>
		<select multiple class="multiple" name="carga[]" id="carga[]" required >
		<?php 
		foreach ($tipocarga as $dato) {
				$id=$dato['id'];
				echo "<option required value=".$dato['nombre']." selected>".$dato['nombre']."</option>";
					
				}

		?>
		</select>
		</td><tr>
			
        <td align="center"><input type="submit" value="Guardar" style='cursor:pointer'></td>
    </table>
</form>


</table>
</div>
	